name: CI
on: [ push, pull_request ]
jobs:
  Build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [ 20 ]
        eslint-version: [ '' ]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Use Node.js ${{matrix.node-version}}
      uses: actions/setup-node@v4
      with:
        node-version: ${{matrix.node-version}}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Install eslint@${{ matrix.eslint-version }}
      if: matrix.eslint-version != ''
      run: |
        npm install eslint@${{ matrix.eslint-version }}
    - name: Build
      run: npm run all
    - name: Upload Coverage
      uses: codecov/codecov-action@v2